Repository hmcts/am-lib, pull requests merged in 2019-07, with the labels that each got.

#233 fix: update invalid arguments provider
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/validation/AttributeSecurityClassificationValidator.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/validation/ValidAttributeSecurityClassification.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceWithSecurityClassificationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceValidationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/InvalidArgumentsProvider.java
  src/test/java/uk/gov/hmcts/reform/amapi/exception/AccessManagementResponseEntityExceptionHandlerTest.java
Labels: ns:am-lib-test-pr-233

#235 feat:ReturnAccessRights - Client Lib Method(Am-290)
  am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/states/BenchmarkState.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/FilterResourceService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/AccessEnvelope.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/AccessResourceEnvelope.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/AccessorListByResourceEnvelope.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceWithSecurityClassificationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceValidationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/FilterResourceServiceValidationTest.java
  src/main/java/uk/gov/hmcts/reform/amapi/config/AccessManagementServiceConfiguration.java
  src/main/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementController.java
  src/test/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementControllerTest.java
Labels: ns:am-lib-test-pr-235

#238 feat: revoke access with optional resource name and service name
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/validation/AttributeSecurityClassificationValidator.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/ExplicitAccessMetadata.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceValidationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/FilterResourceServiceValidationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/InvalidArgumentsProvider.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestDataFactory.java
  src/gatling/resources/revokeResourceAccess.json
  src/test/resources/input-data/revokeResourceAccess.json
Labels: ns:am-lib-test-pr-238

#241 fix: Am-309 Gatling Testing: Default data insertion
  Jenkinsfile_nightly
  build.gradle
  src/gatling/load-or-delete-data-win.bat
  src/gatling/load-or-delete-data.sh
  src/gatling/testdata/delete-data.sql
  src/gatling/testdata/initial-data-load.sql
  src/main/java/uk/gov/hmcts/reform/amapi/Application.java
Labels: ns:am-lib-test-pr-241

#242 fix:Gatling Testing: Default data insertion(AM-309)
  Jenkinsfile_nightly
Labels: ns:am-lib-test-pr-242

#243 fix: terraform module subscription
  infrastructure/main.tf
Labels: ns:am-lib-test-pr-243

#245 fix: gatling fix initial data load Jenkins aat(Am-362)
  Jenkinsfile_nightly
  build.gradle
  src/gatling/load-or-delete-data.sh
Labels: ns:am-lib-test-pr-245

#248 Fix:Gating test Initial data load Jenkins(AM-362)
  Jenkinsfile_nightly
  build.gradle
  src/gatling/load-or-delete-data.sh
Labels: ns:am-lib-test-pr-248

#249 fix: initial test data load(AM-362)
  Jenkinsfile_nightly
Labels: ns:am-lib-test-pr-249

#251 fix:Gating test Initial data load Jenkins(AM-362)
  Jenkinsfile_nightly
  build.gradle
  nightlyperformancedata/load-or-delete-performance-testdata-win.bat
  nightlyperformancedata/load-or-delete-performance-testdata.sh
  nightlyperformancedata/sql/delete-data.sql
  nightlyperformancedata/sql/load-data.sql
Labels: ns:am-lib-test-pr-251

#253 fix:Gating test Initial data load Jenkins(AM-362)
  Jenkinsfile_nightly
Labels: ns:am-lib-test-pr-253

#254 fix:Gating test Initial data load Jenkins(AM-362)
  Jenkinsfile_nightly
Labels: ns:am-lib-test-pr-254

#255 Am 362 initial test data load
  Jenkinsfile_nightly
Labels: ns:am-lib-test-pr-255

#256 Am 362 initial test data load
  Jenkinsfile_nightly
Labels: ns:am-lib-test-pr-256

#252 feat: endpoint for returning resource accessors
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/FilterResourceService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/ResourceAccessor.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/ResourceAccessorsEnvelope.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/FilterResourceServiceValidationTest.java
  nightlyperformancedata/sql/delete-data.sql
  nightlyperformancedata/sql/load-data.sql
  src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/http/AccessManagement.scala
  src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/scenarios/BasicScenarios.scala
  src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/simulations/PipelineSimulation.scala
  src/main/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementController.java
  src/test/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementControllerTest.java
  tools/postman-collections/am-lib-testing.postman_collection.json
Labels: ns:am-lib-test-pr-252

#259 refactor: filter logic to include explicit access for roles
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/FilterResourceService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestDataFactory.java
Labels: ns:am-lib-test-pr-259

#261 fix:AM-374 Duplicate access records are getting created in database
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/resources/db/migration/V17__Alter_Access_Management_Relation_Constraint.sql
Labels: ns:am-lib-test-pr-261

#267 feat:AM-329 Grant explicit access to resource for all(Wildcard)
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/enums/AccessorType.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/resources/db/migration/V16__Alter_Accessor_Type_For_Access_Management.sql
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/helpers/TestDataFactory.java
Labels: ns:am-lib-test-pr-267

#269 fix:out of order flyway
  build.gradle
Labels: ns:am-lib-test-pr-269
