Repository hmcts/am-lib, pull requests merged in 2019-10, with the labels that each got.

#387 feat: revoke functional tests (AM-384)
  src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/FunctionalTestSuite.java
  src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/api/RevokeResourceAccessApiTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/client/AmApiClient.java
Labels: ns:am-accessmgmt-api-pr-387

#396 feat: functional tests for grant access endpoint
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/api/CreateResourceAccessApiTest.java
Labels: ns:am-accessmgmt-api-pr-396

#400 refactor: Default role setup service interface
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/service/DefaultRoleSetupImportService.java
Labels: ns:am-accessmgmt-api-pr-400

#409 feat:Grant Resource Permissions with CCD batch
  am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/SetupGenerator.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceImpl.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/ErrorHandlingAspect.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/DefaultRoleSetupRepository.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/FilterResourceWithSecurityClassificationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetResourceDefinitionsWithCreatePermissionIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GetRolePermissionsIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/ReturnCaseRolesForUserIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/ReturnRolePermissionsForCaseTypeIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/ReturnUserCasesIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/base/PreconfiguredIntegrationBaseTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/helpers/DatabaseHelperRepository.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ResourceDefinitionIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/RoleIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/ServiceIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceValidationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/amapi/controllers/AccessManagementControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/amapi/exception/AccessManagementResponseEntityExceptionHandlerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/amapi/exception/S2SAuthenticationExceptionTest.java
  src/main/java/uk/gov/hmcts/reform/amapi/config/DefaultRoleSetupImportServiceConfiguration.java
Labels: ns:am-accessmgmt-api-pr-409

#410 feat: Return_role_acls_for_casetypes
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceImpl.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/DefaultRoleSetupRepository.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/ReturnRolePermissionsForCaseTypeIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/AccessManagementServiceValidationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceValidationTest.java
Labels: ns:am-accessmgmt-api-pr-410

#412 feat: Return role & ACLs (permissions) for case type(s) to CCD (AM-423)
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceImpl.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/DefaultRoleSetupRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/mappers/RolePermissionsForCaseTypeEnvelopeReducer.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/DefaultRolePermissions.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/models/RolePermissionsForCaseTypeEnvelope.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
  docker-compose.yml
  tools/postman-collections/am-accessmgmt-api.postman_collection.json
Labels: ns:am-accessmgmt-api-pr-412

#414 refactor: parametrized Test case fix and Aspect point cuts paths updated
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/AuditingAspect.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/ErrorHandlingAspect.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/aspects/ValidationAspect.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceValidationTest.java
Labels: ns:am-accessmgmt-api-pr-414

#417 fix: nightly zap fix
  security.sh
Labels: ns:am-accessmgmt-api-pr-417

#418 tests: adding integration tests for AM-423
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/ReturnRolePermissionsForCaseTypeIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
Labels: ns:am-accessmgmt-api-pr-418

#420 build:disable legacy deployment for ASE
  Jenkinsfile_CNP
Labels: ns:am-accessmgmt-api-pr-420

#415 spring api rest port revert
  docker-compose.yml
  tools/postman-collections/am-accessmgmt-api.postman_collection.json
Labels: ns:am-accessmgmt-api-pr-415

#416 refactor: Am audit refactor (AM-418)
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/AccessManagementService.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceImpl.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/models/ExplicitAccessAuditRecord.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/models/ExplicitAccessRecord.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/models/ResourceAttributeAudit.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/models/RoleBasedAccessAuditRecord.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/models/RoleBasedAccessRecord.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/AccessManagementRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/repositories/DefaultRoleSetupRepository.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/internal/utils/PropertyReader.java
  am-lib/src/main/resources/application.properties
  am-lib/src/main/resources/db/migration/V21__Audit_Scripts_AM.sql
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/GrantAccessIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/RevokeAccessIntegrationTest.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/internal/utils/AuditEnabled.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/internal/utils/AuditFlagValidate.java
Labels: ns:am-accessmgmt-api-pr-416

#425 fix: flyway failure fix for audit table
  am-lib/src/main/resources/db/migration/V21__Audit_Scripts_AM.sql
  am-lib/src/main/resources/db/migration/V22__Alter_Audit_Action_Constraint.sql
Labels: ns:am-accessmgmt-api-pr-425

#428 fix: Flyway audit script fix for checksum
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am-accessmgmt-api-pr-428

#430 fix:fixing gradle build warnings
  am-lib/src/benchmark/java/uk/gov/hmcts/reform/amlib/states/DataState.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/ReturnRolePermissionsForCaseTypeIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/internal/utils/PermissionsTest.java
Labels: ns:am-accessmgmt-api-pr-430

#432 revert: flyway repair reverted
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am-accessmgmt-api-pr-432

#429 refactor: Handle batch upload of Case Type ACLs test cases for parametrized and persistence Exception
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceImpl.java
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/service/DefaultRoleSetupImportService.java
  am-lib/src/test/java/integration/uk/gov/hmcts/reform/amlib/importer/DefaultPermissionIntegrationTest.java
  am-lib/src/test/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceValidationTest.java
Labels: ns:am-accessmgmt-api-pr-429

#423 feat: UserTransaction support in AM
  am-lib/build.gradle
  am-lib/src/main/java/uk/gov/hmcts/reform/amlib/DefaultRoleSetupImportServiceImpl.java
Labels: ns:am-accessmgmt-api-pr-423

#433 feat : New Functional Tests for Filter API.
  am-lib/src/main/resources/db/migration/migrationAks/V19__load_data.sql
  src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/FunctionalTestSuite.java
  src/functionalTest/java/uk/gov/hmcts/reform/amapi/functional/api/FilterResourceApiTest.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/load-data-functional.sql
Labels: ns:am-accessmgmt-api-pr-433

#440 fix: nightly fix ingressHost
  charts/am-accessmgmt-api/Chart.yaml
  charts/am-accessmgmt-api/values.yaml
Labels: ns:am-accessmgmt-api-pr-440

#441 fix: flyway path refactor
  am-lib/src/main/resources/db/migrationAks/V19__load_data.sql
Labels: ns:am-accessmgmt-api-pr-441

#442 fix: functional and gatling fix
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/delete-data-functional.sql
  src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/utils/Environment.scala
  src/gatling/simulations/uk/gov/hmcts/reform/amlib/performance/utils/S2SHelper.scala
Labels: ns:am-accessmgmt-api-pr-442

#443 fix: bump up charts version
  charts/am-accessmgmt-api/Chart.yaml
  charts/am-accessmgmt-api/requirements.yaml
Labels: ns:am-accessmgmt-api-pr-443

#444 fix: Spring security firewall fix
  src/main/java/uk/gov/hmcts/reform/amapi/config/AuthCheckerConfiguration.java
Labels: ns:am-accessmgmt-api-pr-444

#452 disable zap security scan
  Jenkinsfile_nightly
Labels: ns:am-accessmgmt-api-pr-452
